name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}

      - name: Build project
        run: ./gradlew clean build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build/libs/*.jar, build/reports/jacoco/test/jacocoTestReport.xml

  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run JaCoCo Coverage
        run: ./show_jacoco_coverage.sh
#          net/yanen/activity/monitor/service/ActivityLogService \
#          net/yanen/activity/monitor/service/DetectionActivityService \
#          net/yanen/activity/monitor/controller/DetectionController \
#          net/yanen/activity/monitor/service/detection/RelativeAmountCheckActions \
#          net/yanen/activity/monitor/service/DetectionService

  dockerize:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }} .
          docker push ${{ secrets.DOCKER_IMAGE }}
