apiVersion: apps/v1
kind: Deployment
metadata:
  name: experimental-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: experimental-app
  template:
    metadata:
      labels:
        app: experimental-app
    spec:
      containers:
        - name: experimental-app-container
          image: bethakzs/experimental:latest
          ports:
            - containerPort: 80