name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'adopt'
          cache: maven

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "bethakzs"
          password: "r1o2m3a4n5"

      - name: Build Docker image
        run: docker build -t bethakzs/your_image_name:latest .

      - name: Push Docker image
        run: docker push bethakzs/your_image_name:latest
